[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1028:Enum Storage should be Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1031:Do not catch general exception types")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1034:Nested types should not be visible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design",        "CA1056:Uri properties should not be strings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1707:Identifiers should not contain underscores")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1714:Flags enums should have plural names")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming",        "CA1717:Only FlagsAttribute enums should have plural names")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance",   "CA1819:Properties should not return arrays")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2007:Consider calling ConfigureAwait on the awaited task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability",   "CA2008:Do not create tasks without passing a TaskScheduler")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE0066:Convert switch statement to expression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style",         "IDE1006:Naming Styles")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage",         "CA2200:Rethrow to preserve stack details.")]
